# Generated by Django 3.1.2 on 2021-03-04 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('porter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=50)),
                ('pick_address', models.CharField(max_length=100)),
                ('drop_address', models.CharField(max_length=100)),
                ('total_amount', models.PositiveIntegerField(max_length=6)),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='porter.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('category_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('contact_no', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='')),
                ('capacity', models.PositiveIntegerField(max_length=6)),
                ('size', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackorder_detail', models.CharField(max_length=100)),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='porter.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.BooleanField(default=False)),
                ('payment_type', models.CharField(max_length=10)),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='porter.booking')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='enterprise_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='porter.enterprise'),
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='porter.vehicle'),
        ),
    ]
