# Generated by Django 3.1.2 on 2021-03-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porter', '0002_auto_20210304_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admindetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('contact_no', models.CharField(max_length=12)),
                ('birth_date', models.DateField(max_length=50)),
            ],
        ),
    ]
