# Generated by Django 3.1.2 on 2021-03-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porter', '0003_admindetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='block_status',
            field=models.BooleanField(default=False),
        ),
    ]
