# Generated by Django 3.1.2 on 2021-03-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porter', '0004_customer_block_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
