# Generated by Django 3.1.2 on 2021-03-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porter', '0007_auto_20210309_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='capacity',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
