# Generated by Django 3.1.2 on 2021-03-10 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('porter', '0008_auto_20210309_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('contact_no', models.CharField(max_length=12)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='porter.city')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='porter.vehicle')),
            ],
        ),
    ]
