# Generated by Django 3.1.2 on 2021-03-18 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('porter', '0010_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='porter.category'),
            preserve_default=False,
        ),
    ]
