# Generated by Django 3.1.2 on 2021-03-22 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('porter', '0012_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='driver_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='porter.driver'),
        ),
    ]
