# Generated by Django 3.1.2 on 2021-03-24 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('porter', '0013_booking_driver_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_status', models.PositiveIntegerField(max_length=2)),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='porter.booking')),
            ],
        ),
        migrations.DeleteModel(
            name='Track',
        ),
    ]
