# Generated by Django 3.1.2 on 2021-03-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porter', '0015_booking_track_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='license_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='driver',
            name='rc_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='drop_address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pick_address',
            field=models.CharField(max_length=500),
        ),
        migrations.DeleteModel(
            name='TrackDetails',
        ),
    ]
