# Generated by Django 3.1.2 on 2021-03-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porter', '0016_auto_20210327_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='block_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='block_status',
            field=models.BooleanField(default=False),
        ),
    ]
