# Generated by Django 3.1.2 on 2021-03-29 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('porter', '0019_enterprise_city_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='porter.category'),
        ),
    ]
